### ISSUE TITLE
Failing for the stacks with LoadBased servers with following error

### ISSUE THREAD

**Issue by Rupasinghe2012** [chaturanga50/opsworks-cli#18]
Traceback (most recent call last):
  File "/usr/local/bin/opsworks-cli", line 14, in <module>
    modules.execute_recipes()    
  File "/usr/local/lib/python2.7/site-packages/modules/execute_recipes.py", line 72, in execute_recipes
    ec2id = instanceid['Ec2InstanceId']
KeyError: 'Ec2InstanceId'

**Comment by chaturanga50** [comment]
unable to replicate this issue. I've tested with the latest version available in pip and running the commands without any issue with LoadBased servers.

**Comment by Rupasinghe2012** [comment]
This happens at the initial level when there is no instance id for the load
based servers.

**Comment by chaturanga50** [comment]
issue fixed in the latest version
