### ISSUE TITLE
Running on Endless loop when we have both Success and Failed instances in the Deployment

### ISSUE THREAD

**Issue by Rupasinghe2012** [chaturanga50/opsworks-cli#19]
Deployment started...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...
Deployment not completed yet..waiting 10 seconds before send request back to aws...

**Comment by chaturanga50** [comment]
fixed with version 0.5.1
